### PR TITLE
Explicitly tag command to avoid deprecation warnings

### LINKED ISSUE #57: Symfony 3.4 & 4.0+ requires commands to be explicitly tagged in services.xml

### PR DESCRIPTION
**Pull request by acrobat**
Fixes #57 and related to #59

### CODE REVIEW

**Comment by alister** [comment]
There are already commands in the services.xml file, but they aren't tagged.

**Comment by acrobat** [comment]
Dang missed those! Moved them to the separate services file and tagged them!

**Comment by alister** [comment]
I've run the PR in my own symfony/symfony:3.4-beta2 app  to test and the `Auto-registration of the command "....\DebugCommand" is deprecated` is solved. 

:+1: 

The services it uses (bernard.command.produce & consume) are also now private-by default in Symfony 3.4, but that is a wider issue for the bundle and all of the services.

I've not looked at the bernard/Commands/Doctrine commands either, and having Symfony commands in the bernard non-bundle does confuse matters.

**Comment by acrobat** [comment]
Thanks for testing @alister! I will create a general issue to test the bundle againt sf 3.4 and fix all the deprecations + also make sure the bundle works for sf4.

The mixed location of commands is indeed something weird and we are not sure where to have them, as they can also be used without the symfony bundle as standalone commands. See bernardphp/bernard#259

**Pull request merged**
