### PR TITLE
SQS driver support

### PR DESCRIPTION
**Pull request by MalteWunsch**
The proposed changes are based on the last tagged version 1.0.1. Should I rebase them against master? (I guess there'll be at least one merge conflict in `Configuration` due to an extract method refactoring)

Solves #11.

### CODE REVIEW

**Comment by henrikbjorn** [comment]
Need to be rebased based on the latest master, thanks :)

**Comment by MalteWunsch** [comment]
@henrikbjorn Rebasing against master would mean to require bernard/bernard 1.0.*@dev, i.e. nobody using only tagged versions will be able to use the SQS support until bernard/bernard 1.0.0.

Our application is not ready for the changes in bernard/bernard 1.0.*@dev (e.g. the dropped support for JMSSerializer), too. And on the one hand, we don't want to have to follow the progressing development there; on the other hand, we don't want to gamble on a stable 1.0.0 being released in the near future.

So we would very much appreciate it if we could merge the PR here for a bernardphp/BernardBundle 1.1.0 (seeing it as a new feature in semantic versioning terms). And I'd be happy to follow-up in another PR merging the 1.1.0 into the master. Would that be okay for you?

**Comment by MalteWunsch** [comment]
Just noticed this PR is against your master, that's wrong of course. My proposal is that we close this one, then I open a new PR with the changes seen here against your 1.0.1, and finally a second PR merging that into your master.

**Comment by MalteWunsch** [comment]
Flaw: I cannot open a pull request against a tag, only against branches. Would it be possible to open a branch starting at 1.0.1 for that? Or is there a better idea?

**Comment by henrikbjorn** [comment]
@MalteWunsch there is a 1.x branch :)

**Comment by MalteWunsch** [comment]
Great!

**Pull request closed without merging**
