### PR TITLE
SQS driver support for 1.x

### PR DESCRIPTION
**Pull request by MalteWunsch**
As a follow up for #12, this one is the PR for SQS driver support in 1.x.

When it's accepted, I'll do another PR for merging it into the current master, which will probably be a little bit more than a pure merge, as I'll try to adapt the new style in the master (array syntax, structure...).

### CODE REVIEW

**Comment by henrikbjorn** [comment]
Seems like this breas with symfony 2.1, is there anyway to add that support back? Otherwise great work on this.

**Comment by MalteWunsch** [comment]
In symfony/DependencyInjection 2.0 - 2.5, [Symfony\Component\DependencyInjection\Definition](https://github.com/symfony/DependencyInjection/blob/2.5/Definition.php) has the setFactory{Class, Method, Service}-methods. The versions 2.6 - 2.8 have them deprecated, which generates an error in the unit tests, and offer the new setFactory method as a replacement. Finally, symfony/DependencyInjection 3.0 will only have the setFactory method.

In 866b29c4da2bba2f7a063863e96c4bcccb722145, I tried to distinguish the versions by \Symfony\Component\HttpKernel\Kernel::MAJOR_VERSION == 2 && Kernel::MINOR_VERSION < 6, but somehow Travis managed to install Symfony 2.2.* with a symfony/DependencyInjection >= 2.6, which gives us the errors in [the latest Travis builds](https://travis-ci.org/bernardphp/BernardBundle/builds/65248061).

Any ideas?
* Ignoring it seems to be out of the question, as we probably don't want to provide a version with failing tests.
* We could check with method_exists() wether the setFactory method exists, but this seems dirty to me, as it carries no semantics.
* We could go for the old methods and restrict symfony/DependencyInjection to be < 2.6 in the composer.json
* We may be able to suppress the E_USER_DEPRECATED warnings in the tests, but I don't like that either.

So far method_exists seems to be the best option to me, garnished with a comment or self documenting method name.

**Comment by MalteWunsch** [comment]
@henrikbjorn Agreed?

**Comment by henrikbjorn** [comment]
I think the method exists is best or there isnt another way of obtaining the api version.

**Comment by MalteWunsch** [comment]
Ready for merge then, and after that I'll do the PR merging it into the master.

**Comment by henrikbjorn** [comment]
Looks good, thanks for your work on this :+1:

**Comment by MalteWunsch** [comment]
Thank you very much!

One last thing: would you please tag the merged version? I propose 1.1.0 as the SQS driver support is a new feature in semantic versioning terms.

**Pull request merged**
